#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

lockfile=.precommit-lock
echo "precommit"
if [ ! -e $lockfile ]
then
  echo "no lock file"
  touch $lockfile
  yarn doc
  git commit --amend --no-edit
  rm -f $lockfile
fi
